name: expense
networks:
  default:
    name: expense
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql
  backend:
    image: backend
    container_name: backend
    depends_on:
      - mysql
  frontend:
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      -"80:80"